---
- name: MAIN TASK | Installing and configuring NextCloud
  hosts: all
  vars_files:
    - defaults/main.yml
    - vars/main.yml
  remote_user: root
  tasks:

## Please notice that HOSTS is set to ALL by default.  This is because I use this in Ansible Tower
## and I limit my hosts accordingly.  Please use the syntax in the README file to specify hosts.
##	Just for one extra step....
## This requires the safety word to be passed in order for this playbook to do anything.
## I really want to make sure you read through this and know what you're doing.  So read
## the README or just remove the next 3 lines to avoid passing a safety word.
    - name: "Checking for {{ ncsrvfile }} to see if this is supposed to be a nextcloud server."
      stat:
        path: "{{ ncsrvfile }}"
      register: isncsrv

    - name: "Stopping here if there is no {{ ncsrvfile }} on the server"
      fail:
        msg: "Please create an empty file on the server called {{ ncsrvfile }} before you run this playbook"
      when: isncsrv.stat.exists == False

    - name: "Stopping here if the safety word is not passed"
      fail:
        msg: "Please pass the safety word or remove this fail section from nextcloud-remove.yml"
      when: safety_word is undefined or safety_word != "nextcloud-remove"

    - include: tasks-remove/main.yml


