---
- name: "set PHP post max size"
  lineinfile:
    dest: /etc/php.ini
    state: present
    regexp: '^post_max_size\s'
    line: 'post_max_size = 50M'

- name: "set PHP upload max size"
  lineinfile:
    dest: /etc/php.ini
    state: present
    regexp: '^upload_max_size\s'
    line: 'upload_max_size = 50M'

- name: "copy autoconfig template into {{ ncwebpath }}/config/autoconfig.php"
  template:
    src: templates/autoconfig.php
    dest: "{{ ncwebpath }}/config/autoconfig.php"
    owner: apache
    group: apache
    mode: 0644

- name: "set apache ownership on {{ ncwebpath }}"
  file:
    path: "{{ ncwebpath }}"
    state: directory
    recurse: yes
    owner: apache
    group: apache

- name: "Set selinux context recursively httpd_sys_rw_content_t {{ ncwebpath }}"
  raw: "chcon -R -t httpd_sys_rw_content_t {{ ncwebpath }}"

- name: "Change httpd.conf to make the web root {{ ncwebpath }}"
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^DocumentRoot '
    line: 'DocumentRoot "{{ ncwebpath }}"'

- name: "Create a new database {{ ncdbname }}"
  mysql_db:
    name: "{{ ncdbname }}"
    state: present

- name: "Create the user {{ ncdbuser }}"
  mysql_user:
    name: "{{ ncdbuser }}"
    host: localhost
    password: "{{ ncdbpass }}"
    priv: "{{ ncdbname }}.*:ALL"
    state: present

