---
- name: set PHP post max size
  lineinfile:
    dest: /etc/php.ini
    state: present
    regexp: '^post_max_size\s'
    line: 'post_max_size = 50M'

- name: set PHP upload max size
  lineinfile:
    dest: /etc/php.ini
    state: present
    regexp: '^upload_max_size\s'
    line: 'upload_max_size = 50M'

- name: autoconfig
  template:
    src: templates/autoconfig.php
    dest: /var/www/nextcloud/config/autoconfig.php
    owner: apache
    group: apache
    mode: 0644

- name: set ownership on the web dir to apache
  file:
    path: /var/www/nextcloud/
    state: directory
    recurse: yes
    owner: apache
    group: apache

- raw: "chcon -R -t httpd_sys_rw_content_t /var/www/nextcloud/"

- name: Change httpd.conf to make the web root "/var/www/nextcloud"
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^DocumentRoot '
    line: 'DocumentRoot "/var/www/nextcloud"'

- name: Create a new database
  mysql_db:
    name: "{{ ncdbname }}"
    state: present

- mysql_user:
    name: "{{ ncdbuser }}"
    host: localhost
    password: "{{ ncdbpass }}"
    priv: "{{ ncdbname }}.*:ALL"
    state: present

