---
- name: "Checking to see if httpd.conf exists"
  stat:
    path: "{{ httpdconf }}"
  register: iscfghttpd

- name: "checking to see if nextcloud is set as the DocumentRoot"
  shell: 'egrep "^DocumentRoot" /etc/httpd/conf/httpd.conf 2>&1 | egrep "DocumentRoot \"/var/www/nextcloud\"" | wc -l'
  register: iscfghttpdset
  changed_when: iscfghttpdset.stdout == "0"




- debug:
    msg: "Does the httpd.conf file exist?  {{ iscfghttpd.stat.exists }}"
  when: iscfghttpd.stat.exists == True

- debug:
    msg: "Does the httpd.conf have the correct settings?  {{ iscfghttpdset.stdout }}"
  when: iscfghttpdset.stdout == "0"

