---
- name: installing the required software
  become: yes

  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - unzip
    - MySQL-python
    - mysql-connector-python
    - policycoreutils-python
    - httpd
    - mariadb
    - mariadb-server
    - php56u
    - php56u-cli
    - php56u-common
    - php56u-gd
    - php56u-imap
    - php56u-intl
    - php56u-mbstring
    - php56u-mcrypt
    - php56u-mysqlnd
    - php56u-process
    - php56u-xml

- name: "Checking to see if {{ ncwebpath }} already exists."
  stat:
    path: "{{ ncwebpath }}"
  register: pnc

- name: "do not allow this playbook to overwrite an existing nextcloud instance"
  fail:
    msg: "{{ ncwebpath }} already exists.  Cannot complete"
  when: pnc.stat.isdir is defined and pnc.stat.isdir

- name: "Clear the tmp location"
  file:
    path: /tmp/nextcloud
    state: absent

- name: "download and unarchive nextcloud 11.0.0 stable to /tmp"
  unarchive:
    src: "{{ ncsource }}"
    dest: /tmp/
    remote_src: True

- name: "Copy files from /tmp to {{ ncwebpath }}"
  command: "/bin/mv /tmp/nextcloud/ {{ ncwebpath }}"
  args:
    creates: "{{ ncwebpath }}"


