---
- name: "Checking to see if httpd is installed prior to us installing it"
  stat:
    path: "/usr/lib/systemd/system/httpd.service"
  register: wassvchttpd

- name: "Checking to see if mariadb is installed prior to us installing it"
  stat:
    path: "/usr/lib/systemd/system/mariadb.service"
  register: wassvcmaria

- name: installing the required software
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - unzip
    - MySQL-python
    - mysql-connector-python
    - policycoreutils-python
    - httpd
    - mariadb
    - mariadb-server
    - php56u
    - php56u-cli
    - php56u-common
    - php56u-gd
    - php56u-imap
    - php56u-intl
    - php56u-mbstring
    - php56u-mcrypt
    - php56u-mysqlnd
    - php56u-process
    - php56u-xml

