---
- name: installing | installing the required software
  become: yes

  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - unzip
    - MySQL-python
    - mysql-connector-python
    - policycoreutils-python
    - httpd
    - mariadb
    - mariadb-server
    - php56u
    - php56u-cli
    - php56u-common
    - php56u-gd
    - php56u-imap
    - php56u-intl
    - php56u-mbstring
    - php56u-mcrypt
    - php56u-mysqlnd
    - php56u-process
    - php56u-xml

- name: check to see if nextcloud path already exists.
  stat:
    path: /var/www/nextcloud
  register: pnc

- name: do not allow this playbook to overwrite an existing nextcloud instance
  fail:
    msg: "/var/www/nextcloud already exists.  Cannot complete"
  when: pnc.stat.isdir is defined and pnc.stat.isdir

- name: download and unarchive nextcloud 11.0.0 stable
  unarchive:
    src: https://download.nextcloud.com/server/releases/nextcloud-11.0.0.zip
    dest: /var/www/
    remote_src: True

