---
- name: "Remove database {{ ncdbname }}"
  mysql_db:
    name: "{{ ncdbname }}"
    state: absent
  ignore_errors: yes

- name: "Remove the user {{ ncdbuser }} for {{ ncdbname }}.*:ALL"
  mysql_user:
    host: localhost
    name: "{{ ncdbuser }}"
    password: "{{ ncdbpass }}"
    priv: "{{ ncdbname }}.*:ALL"
    update_password: always
    state: absent
  ignore_errors: yes
